name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Run Gradle build (action)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon --stacktrace

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: fabric-optmod-jar
          path: build/libs/*.jar
